name: 'Delete Release/Tag'

description: 'Deletes GitHub releases or tags based on a keyword.'
author: Shivam 
branding:
  icon: clipboard
  color: blue

inputs:
  token:
    description: 'GitHub token with repo scope.'
    required: true
  repo:
    description: 'The name of the repository.'
    required: true
  owner:
    description: 'owner of repo.'
    required: true
  keyword:
    description: 'Keyword to match for deletion.'
    required: true
  deletetype:
    description: 'Keyword to match for deletion.'
    required: true

runs:
  using: docker
  image: Dockerfile
  args:  
    - ${{ inputs.token }}
    - ${{ inputs.repo }}
    - ${{ inputs.keyword }}
    - ${{ inputs.owner }}
    - ${{ inputs.deletetype }}
